[versions]
agp = "8.5.0"
kotlin = "1.9.0"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.9.3"
composeBom = "2024.04.01"
navigationCompose = "2.8.5"
dagger-hilt = "2.51.1"
room_version = "2.6.1"
hilt-navigation-compose = "1.2.0"
material = "1.7.6"
lifecycle-viewmodel-compose="2.8.7"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-compose-material={group = "androidx.compose.material", name = "material", version.ref = "material"}

lifecycle-viewmodel-compose={group="androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref="lifecycle-viewmodel-compose"}

#hilt
dagger-hilt-dependency = {group = "com.google.dagger", name = "hilt-android", version.ref = "dagger-hilt"}
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "dagger-hilt" }
hilt-navigation-compose = {group = "androidx.hilt", name="hilt-navigation-compose", version.ref = "hilt-navigation-compose" }


#room
room-runtime= {group="androidx.room", name = "room-runtime", version.ref = "room_version"}
room-compiler= {group="androidx.room", name = "room-compiler", version.ref = "room_version"}
room-ktx= {group="androidx.room", name = "room-ktx", version.ref = "room_version"}


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
dagger-hilt-android = {id= "com.google.dagger.hilt.android", version.ref = "dagger-hilt"}

#implementation "androidx.lifecycle:lifecycle-viewmodel-compose:2.4.0-beta01"

